# Generated by Django 5.0.6 on 2025-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_medicaldocument_document_type_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='advance_directive_details',
            field=models.TextField(blank=True, help_text='Details on living will, healthcare proxy, etc.', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='alcohol_consumption',
            field=models.CharField(blank=True, help_text='None, Occasional, Moderate, Heavy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='Last recorded blood pressure', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Ongoing health conditions requiring management', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='exercise_habits',
            field=models.CharField(blank=True, help_text='Frequency and type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_medical_history',
            field=models.TextField(blank=True, help_text='Medical conditions present in immediate family members', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='has_advance_directive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(blank=True, default='English', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_pharmacy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_status',
            field=models.CharField(blank=True, help_text='Never, Former, Current (packs/day)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='vaccination_history',
            field=models.TextField(blank=True, help_text='Major vaccinations received and dates', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Medications, food, environmental allergies and reactions', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Include dosage, frequency, and duration', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_medical_history',
            field=models.TextField(blank=True, help_text='Previous significant illnesses, surgeries, hospitalizations', null=True),
        ),
    ]
